### ISSUE TITLE
minio.error.S3Error: S3 operation failed; code: InvalidAccessKeyId

### ISSUE THREAD

**Issue by tamis-laan** [minio/minio-py#1171]
The following very basic setup fails with `InvalidAccessKeyId` and I don't see why, bug?:

Python:
``` python
# Import minio
from minio import Minio

# Create minio connection
minio = Minio(
    "minio:9000",
    access_key="key",
    secret_key="secret",
    secure=False
)

# Check if bucket exists
result = minio.bucket_exists('bucket')

# Make the bucket if it does not exists
if not result:
    minio.make_bucket('bucket')
```

Docker compose yaml:
``` yaml
  # Object Store
  minio:
    hostname: "minio"
    image: minio/minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioroot"
      MINIO_ROOT_PASSWORD: "minioroot"
      MINIO_ACCESS_KEY: "key"
      MINIO_SECRET_KEY: "secret"
    command: server --console-address :9001 /data
```

Full Error:
``` bash
minio.error.S3Error: S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /bucket, request_id: 16C490B8364E9E7E, host_id: 560ced32-28e7-4db2-b686-5010d140538b, bucket_name: bucket
```
