### ISSUE TITLE
Metadata unavailable when listing objects

### ISSUE THREAD

**Issue by davidssand** [minio/minio-py#1173]
## Problem

Metadata is empty when listing objects with both `include_user_meta` and `include_version` set to True.

## Demonstration

```

from minio import Minio
from minio.versioningconfig import VersioningConfig, ENABLED

BUCKET = 'mybucket'
ENDPOINT = 'localhost:9000'
ACCESS_KEY = 'minio'
SECRET_KEY = 'minio123'

client = Minio(
    ENDPOINT,
    access_key=ACCESS_KEY,
    secret_key=SECRET_KEY,
    secure=False
)

if not client.bucket_exists(BUCKET):
    client.make_bucket(BUCKET)

client.set_bucket_versioning(BUCKET, VersioningConfig(ENABLED))

message = b"hello"

client.put_object(
    BUCKET, "object_name1", io.BytesIO(message), len(message),
    metadata={"my-metadata": 'This is my metadata'},
)

[
    o.metadata for o in list(
        client.list_objects(BUCKET, include_user_meta=True, include_version=True)
    )
]

>>> [{}]
```

## Expected behavior
The expected behavior happens when I set `include_version` to False:

```
[
    o.metadata for o in list(
        client.list_objects(BUCKET, include_user_meta=True, include_version=False)
    )
]

>>> [{'content-type': 'application/octet-stream',
  'X-Amz-Meta-My-Metadata': 'This is my metadata'}]
```

## My environment

- Python version:
Python 3.9.7

- Installed python Minio SDK information:
Name: minio
Version: 7.1.2
Summary: MinIO Python SDK for Amazon S3 Compatible Cloud Storage
Home-page: https://github.com/minio/minio-py
Author: MinIO, Inc.
Author-email: dev@min.io
License: Apache License 2.0
Requires: certifi, urllib3

## Minio

Minio is running on docker. Here is the docker-compose:

```
minio:
    container_name: "minio"
    image: minio/minio:latest
    entrypoint: minio server --console-address ":9001" /data{1...4}
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ~/minio_data/data1:/data1
      - ~/minio_data/data2:/data2
      - ~/minio_data/data3:/data3
      - ~/minio_data/data4:/data4
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 5
```
